[build]
  publish = "./"
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  command = "echo 'No dev command needed'"
  targetPort = 8080
  port = 8888
  publish = "./"
  autoLaunch = true
